import numpy.typing as npt

class StateVector:
    def __init__(self, state: object) -> None: ...
    def measure(self, modes: list[int] | None = None) -> dict[str, float]: ...

class BasicState:
    def __init__(self, fs: FockState | int | list[int] | tuple[int] | list[float] | tuple[float] | tuple[tuple[int]] | tuple[tuple[float]] | npt.ndarray | str | None) -> None: ...

class FockState:
    def __init__(self, occupation: list[int] | tuple[int, ...]) -> None: ...
