class StateVector:
    def __init__(self, state: object) -> None: ...
    def measure(self, modes: list[int] | None = None) -> dict[str, float]: ...

class BasicState:
    def __init__(self, occupation: list[int] | tuple[int, ...]) -> None: ...

class FockState:
    def __init__(self, occupation: list[int] | tuple[int, ...]) -> None: ...
