class Processor:
    def __init__(self, *args, **kwargs) -> None: ...  # type: ignore[no-untyped-def]
    def add(self, component: object, position: int) -> None: ...
    def linear_circuit(self, circuit: object) -> None: ...
