from perceval.components.linear_circuit import ACircuit
from perceval.utils.states import BasicState, StateVector

class Simulator:
    def __init__(self, backend: object) -> None: ...
    def set_heralds(self, heralds: list[int] | dict[int, int]) -> None: ...
    def clear_heralds(self) -> None: ...
    def set_min_detected_photons_filter(self, threshold: int) -> None: ...
    def keep_heralds(self, value: bool) -> None: ...
    def set_circuit(self, circuit: ACircuit, m: int | None = None) -> None: ...
    def evolve(self, input_state: BasicState | StateVector) -> StateVector: ...
