from perceval.components.experiment import Experiment

class AProcessor:
    def __init__(self, experiment: Experiment | None) -> None: ...
    def add(self, mode_mapping: int | list[int] | dict[int, int], component: object, keep_port: bool = True) -> AProcessor: ...
