from perceval.backends import ABackend
from perceval.components.experiment import Experiment
from perceval.components.linear_circuit import ACircuit, Circuit
from perceval.utils.noise_model import NoiseModel

class Processor:
    def __init__(self, backend: ABackend, m_circuit: int | ACircuit | Experiment | None,
                 noise: NoiseModel | None, name: str = "Local processor") -> None: ...
    def add(self, mode_mapping: int | list[int] | dict[int, int], component: object, keep_port: bool = True) -> Processor: ...
    def linear_circuit(self, flatten: bool = False) -> Circuit: ...
    @property
    def circuit_size(self) -> int: ...
