class StateVector:
    def __init__(self, state: object) -> None: ...
    def m(self) -> int: ...

class FockState:
    def __init__(self, state: object) -> None: ...

class FSArray:
    def __init__(self, m: int, n: int, mask: FSMask | None = None) -> None: ...

class FSMask:
    def __init__(self, m: int, n: int, conditions: list[str] | str | None = None, unbounded_modes: list[int] | None = None) -> None: ...

class BSDistribution:
    def __init__(self, fs: StateVector | None = None, bsd: SVDistribution | dict[FockState, float] | None = None, fsa: FSArray | None = None, probs: list[float] | None = None) -> None: ...

class SVDistribution:
    def __init__(self, fs: FockState | None = None, sv: StateVector | None = None, bsd: BSDistribution | dict[FockState, float] | None = None) -> None: ...

class PostSelect:
    def __init__(self, expression: str) -> None: ...

class BSSamples:e