from perceval.states import BasicState, StateVector

class SVDistribution:
    def __init__(self, state_vector: StateVector) -> None: ...

class PostSelect:
    def __init__(self, condition: object) -> None: ...

class BSDistribution:
    def __init__(self, basic_state: BasicState) -> None: ...
    def sample(self, n_samples: int) -> list[BasicState]: ...

class BSSamples:
    def __init__(self, samples: list[BasicState]) -> None: ...
